Related to #110 supply endpoint metrics (openmetrics)
GluuFederation/gluu-passport pull request #112
Opened 2020-08-28 15:16 UTC by christian-hawk

Related to issue #110 .

- [ ] Tests
- [ ] Create metrics endpoint
- [ ] Regex URL paterns
- [ ] Create middleware

2020-09-01 15:16 UTC, christian-hawk commented
- [ ] fix tests unexpected behavior

2020-09-09 02:34 UTC, christian-hawk commented
- included BDD on TDD proccess (cucumber-js)
- OpenMetrics for endpoints (`/passport/metrics`)
- Fixed tests

2020-09-10 10:11 UTC, kdhttps requested changes
@christian-hawk I really don't know whole the code flow but I tried my best to grab the things and requested for some changes. Also we are using `eslint` code standard so we should fix the issue in every file.

2020-09-10 10:11 UTC, kdhttps commented on test/idp-initiated.test.js
> +{1
1...?

2020-09-10 10:11 UTC, kdhttps commented on test/testdata/init-mock.js
> +
It will be good to keep only one new line

2020-09-10 10:14 UTC, kdhttps commented
Also @christian-hawk  I would like to suggest to follow `Semantic Commit Message` which describe the commit in shorts and helpful.
here is the details https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

2020-09-10 13:34 UTC, christian-hawk commented on package.json
> +    "got": "^11.6.0",
@kdhttps actually it's on dev because right now is used only in testing.

2020-09-10 13:34 UTC, christian-hawk commented on test/app.init.test.js
> +})
agree

2020-09-10 13:34 UTC, christian-hawk commented on test/idp-initiated.test.js
> +{1
lol thx

2020-09-10 13:34 UTC, christian-hawk commented on test/testdata/init-mock.js
> +
agree

2020-09-10 13:39 UTC, kdhttps commented on package.json
> +    "got": "^11.6.0",
I see. Ok

2020-09-10 13:40 UTC, kdhttps commented on package.json
> +    "got": "^11.6.0",
what you think about `eslint` and `author` thing?

2020-09-10 14:05 UTC, kdhttps approved these changes

2020-09-10 14:26 UTC, merged