Added standard JS code linting and refactor code
GluuFederation/gluu-passport pull request #114
Opened 2020-09-14 08:32 UTC by kdhttps

close #109 

Added Standard JS Code listing and formatting. Zero configurations, more details https://standardjs.com/

2020-09-15 02:25 UTC, christian-hawk requested changes
Thanks for this @kdhttps ! 
Please check my minor change request feel free to discuss it.

2020-09-15 02:25 UTC, christian-hawk commented on test/app.init.test.js
> +      // eslint-disable-next-line no-unused-expressions
Hey @kdhttps What if we use https://www.npmjs.com/package/eslint-plugin-chai-friendly instead of the comments?

2020-09-15 07:53 UTC, kdhttps commented on test/app.init.test.js
> +      // eslint-disable-next-line no-unused-expressions
I tried but standard-js has no rules overwrite configuration facility. I guess we are trying to configuring this globally so we can configure it file_globally for specific file by adding `eslint-disable-next-line no-unused-expressions` flag at the top of the file. @christian-hawk what you think?

2020-09-16 09:03 UTC, kdhttps commented
@christian-hawk so I've added [standardx](https://github.com/standard/standardx) by which we can use standard js feature as well as overwrite some custom rules so we have both features now, also fixed the `no-unused-expressions`. Please review

2020-09-16 14:20 UTC, christian-hawk approved these changes
Approved, nice job.

2020-09-16 14:35 UTC, merged