fix(security): bump major versions from passport-saml and uuid
GluuFederation/gluu-passport pull request #151
Opened 2020-11-17 20:29 UTC by christian-hawk

close #146 #148

2020-11-19 07:35 UTC, kdhttps requested changes
@christian-hawk requested for little change. also need to update branch with base branch

2020-11-19 07:35 UTC, kdhttps commented on server/utils/logging.js
> +  path.join(__dirname, 'logs'), process.env.NODE_LOGGING_DIR)
what you think to use vallina js here instead on ramda? If yes then we should refactor this at every place.

2020-11-19 10:03 UTC, christian-hawk commented on server/utils/logging.js
> +  path.join(__dirname, 'logs'), process.env.NODE_LOGGING_DIR)
Good idea mate, thanks!
so for `R.defaultTo` I created a helper function in `misc.js` and replaced all `R.defaultTo` in `logging.js`

If you want feel free to raise an issue to refactor all R.defaultTo, I may take care of it.

Thanks for the good review.

2020-11-20 06:30 UTC, kdhttps requested changes

2020-11-20 06:30 UTC, kdhttps commented on server/utils/logging.js
> +)
@christian-hawk mate, I think we can easily handle this using `||` operator, no need for extra function
for example:
Instead of above code, we can do this like
```
const dir = process.env.NODE_LOGGING_DIR || path.join(__dirname, 'logs')
```
second value is default value here.

2020-11-20 06:30 UTC, kdhttps commented on server/utils/logging.js
> +  }
here its like `msg = msg || '' `

2020-11-20 09:19 UTC, christian-hawk commented on server/utils/logging.js
> +)
Didn't knew about logical OR `||` operator on JS. thank you so much for that 👍🏻 I learn everyday w/ u.

So `R.defaultTo` is totally useless when uncurried!
Wish I knew this before ahahahah

2020-11-25 08:35 UTC, kdhttps approved these changes

2020-11-25 08:35 UTC, merged