refactor(cache-provider.js): update redis deps
GluuFederation/gluu-passport pull request #152
Opened 2020-11-18 14:14 UTC by kdhttps

update redis deps to fix security vulnerability

little fix to handle redis connection functionality retryStrategy

closes #145

2020-11-18 23:38 UTC, christian-hawk requested changes
Hey mate thanks for the PR. 👍🏻 
Please check the conversations I requested some changes and asked some doubts that may require or not more changes.

2020-11-18 23:38 UTC, christian-hawk commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
`PasssportSamlStrategy` returns undefined if fails, instead of throwing Error?

2020-11-18 23:38 UTC, christian-hawk commented on server/cache-provider.js
> +const retryStrategy = (options) => {
Is it testable?
As we use TDD for creating functions for a while, please let me know if I can help.

The unit tests should be done before coding to ensure quality.

Anyway In this case is important to **create unit test** for:
1. `throw new Error('The redis server refused the connection')` 
2. `throw new Error('Redis connection retry time exhausted')`
3. `built in error` (it throws?)
4. `return reconnect...`

May you please explain me what does this function do and why?

2020-11-18 23:38 UTC, christian-hawk commented on server/cache-provider.js
> +  options = R.mergeLeft(options, { retry_strategy: retryStrategy })
any chance that do it with vanilla instead of `ramda`?

2020-11-18 23:38 UTC, christian-hawk commented on server/cache-provider.js
>  function getRedisProvider (options, exp) {
May you create a test for this function?

2020-11-19 07:53 UTC, kdhttps commented on test/providers.test.js
> +    const testProvider = testConfig.passportConfigAuthorizedResponse.providers.find(p => p.id === 'saml-redis-test')
sure, thanks

2020-11-19 07:56 UTC, kdhttps commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
It will throw error when failed to save data in redis. For now it always init strategy because In cache provider, it only returning config

2020-11-19 10:28 UTC, christian-hawk commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
what about try/catch?

2020-11-19 10:40 UTC, christian-hawk commented on server/cache-provider.js
> +const retryStrategy = (options) => {
When you can please answer mainly the last line question: May you please explain me what does this function do and why?

So we can earn some time without another possible change request, if you agree.

2020-11-19 11:53 UTC, kdhttps commented on server/cache-provider.js
> +  options = R.mergeLeft(options, { retry_strategy: retryStrategy })
sure

2020-11-19 11:56 UTC, kdhttps commented on server/cache-provider.js
> +const retryStrategy = (options) => {
In old version, they handle internally by no. of attempt but instead of attempt we can now handle on our own by passing this custom handle function. 
I'll handle `built in error (it throws?)` but I am not getting idea about others

2020-11-19 14:24 UTC, kdhttps commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
I think no need

2020-11-19 14:24 UTC, kdhttps commented on server/cache-provider.js
>  function getRedisProvider (options, exp) {
Sure

2020-11-19 14:42 UTC, kdhttps commented
@christian-hawk added more test cases to test `cache-provider.js` 

```
1. throw new Error('The redis server refused the connection')
2. throw new Error('Redis connection retry time exhausted')
3. built in error (it throws?)
4. return reconnect...
```

covered 3rd point, please suggest or welcome your test code :)

2020-11-19 14:49 UTC, christian-hawk commented on server/cache-provider.js
> +const retryStrategy = (options) => {
Maybe this can help: 
https://github.com/GluuFederation/gluu-passport/blob/eb08980dc5e5e09dec3fa1b0e95eb7e142321673/test/misc.test.js#L18

2020-11-19 14:55 UTC, christian-hawk commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
I gonna disagree here mate. 
As far as I understand, the Error is thrown by an outside dependency, so we should use `try/catch` that will delegate this responsability to the dependency and avoid unecessary code. Also returning undefined and commenting should be avoided according to Clean Code Principles.

2020-11-19 14:59 UTC, christian-hawk commented on test/cache-provider.test.js
> +const chai = require('chai')
this is nice!

2020-11-23 07:23 UTC, kdhttps commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
agree, I'll add try/catch.

2020-11-23 07:37 UTC, kdhttps commented on server/cache-provider.js
> +const retryStrategy = (options) => {
I guess `cache-provider.test.js` test cases covered this, let me know mate if you need any changes

2020-11-23 07:38 UTC, kdhttps commented on test/providers.test.js
> +    const oPassportSAMLStrategy = new PassportSAMLStrategy(testProvider.options, (profile, done) => { })
Pushed changes about this. Please review PR again Mate

2020-11-27 15:38 UTC, christian-hawk commented
run tests

2020-11-27 15:38 UTC, christian-hawk commented
Can one of the admins verify this patch?

2020-11-27 19:12 UTC, kdhttps commented
> Can one of the admins verify this patch?

Sorry Mate, not getting you? Could you please give me some details?

2020-11-27 23:36 UTC, christian-hawk commented
> > Can one of the admins verify this patch?
> 
> Sorry Mate, not getting you? Could you please give me some details?

ahhaha don't worry, it's a jenkins message when build fails..

2020-11-30 14:19 UTC, kdhttps commented
@christian-hawk mate, could you please review this PR ?

2020-12-07 01:29 UTC, christian-hawk commented
run tests

2020-12-07 01:30 UTC, christian-hawk approved these changes
nice, mate!

2020-12-07 01:49 UTC, merged