Added rate-limiting facility
GluuFederation/gluu-passport pull request #163
Opened 2020-11-23 15:31 UTC by kdhttps

Used express-rate-limit package, currently fetching configurations from `production.js` file

closes #139

2020-11-24 23:23 UTC, christian-hawk requested changes
Very nice that you created BDD scenario integration tests for new feature 👏🏻 
I just need to understand (as commented) how it behaves.

I would also request the following change:

unit test `rate-limiter.test.js` for `rate-limiter.js` can be created (actually using TDD the test should be created before developing), for example:
I will also add TDD metodology examples, to illustrate the metodology applied to the current simple file.

- assert that `window` exists (TDD: test will break, so now you can create the first line of code in `rate-limiter.js`: `let window`, test passes...)
- assert that `window` is a `const` (TDD: test will break, so now to pass you can just `const window = ''`, test passes)
- assert that `window` has the same value from `default.js`, `test.js` or `production.js` (TDD: test break... test will pass when you rafactor `const window` to receive `config.get...`, test passes)
- assert that `max` exists (TDD: test will break, so now you can create `let max`, test passes...)
- assert that `max` is a `const` (TDD: test will break, so now to pass you can just `const max = ''`, test passes)
- assert that `max` has the same value from `default.js`, `test.js` or `production.js` (TDD: test break... test will pass when you rafactor `const max` to receive `config.get...`)
- assert that `rateLimit` exists (TDD: after this test we create `rateLimit` (like `let rateLimit`) in `rate-limiter.js` file, so test passes)
- assert that `rateLimit` is strict equal `require('express-rate-limit')`  (TDD: test will break, cause `rateLimit` has not this value. So now we refactor existing rateLimit to `const rateLimit = require('express-rate-limit')` - test passes
- assert that `rateLimiter` is equal `rateLimit){...}`. (TDD: test will break, so you code `= rateLimit({...}))`, test passes

I hope my comments are useful.

2020-11-25 09:06 UTC, kdhttps commented on server/rate-limiter.js
> +  config.has('rateLimitWindowMs') && config.get('rateLimitWindowMs')
> As config module works loading default.js and overriding it's values with others (in our case production.js and test.js.

Wow, I really don't know about this feature. thanks mate, I'll make a changes

2020-11-25 09:07 UTC, kdhttps commented on server/rate-limiter.js
> +const rateLimit = require('express-rate-limit')
Agree

2020-11-25 09:21 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  try {
Mate, I've added note about this in `rate-limiting.feature` file

```
  below test cases are using test.js config. Current rate limit is 45. 
  In first step, we requested only 3 times to successfully reach limit i.e. 45 
  because we already requested 42 time in endpoint-metrics-steps.js test cases
```

```
Given requesting application 3 times + endpoint-metrics-steps.js test cases = 45
```

I understand that this static number is not good. we may face problem in future. we have to find some dynamic way here.

I think we have to start fresh server, atleast for this case. I've tried to separately start server but not getting any success.  Cucumber execute every `Before` block first and in result we get `8090 already in used address` error.

we have to find some dynamic way here. Please provide your suggestion

2020-11-25 09:33 UTC, kdhttps commented on test/features/rate-limiting.feature
> +Feature: Rate limiting
> As you are running integration and behavioral tests (not unit tests), we are not asserting if error is thrown, we are asserting endpoint response.

Understood.

about comments, we need to finalise first this https://github.com/GluuFederation/gluu-passport/pull/163#discussion_r530220214

2020-11-25 09:45 UTC, kdhttps commented on test/app-factory.test.js
agree, my bad, I missed to notice `describe('csurf middleware`

2020-11-25 11:47 UTC, kdhttps commented
> unit test rate-limiter.test.js for rate-limiter.js can be created (actually using TDD the test should be created before developing), for example:
I will also add TDD metodology examples, to illustrate the metodology applied to the current simple file.

@christian-hawk  my friend, Actually my first code was like 
```
const rateLimit = require('express-rate-limit')
const config = require('config')

const rateLimiter = rateLimit({
  windowMs: config.get('rateLimitWindowMs'),
  max: config.get('rateLimitMaxRequestAllow'),
  message: `You have exceeded the max requests`,
  headers: true
})
```

I covered test-cases about it in `app-factory.test.js` 
but
before push code, I though to change message and due to message, I took extra two variables and forgot to cover test cases about new code refactor, my mistake.

I pushed review changes, please review again and thank you for great review :)

2020-11-25 12:18 UTC, christian-hawk commented on test/features/steps/rate-limiting-steps.js
> +  try {
Agree with you.

Let's go each one of the topics you mentiones.

Dinamically using gherkin:
```gherkin
Scenario Outline: rateLimiter should block high rates

Given rate limit is <rateLimitMax> in <rateLimitWindow>
When the endpoint is requested <requestsCount> times in less then <rateLimitMax> by the same client
Then response status code should be <responseStatusCode>
  And response body should be "<responseBody>"

  Examples:

  | rateLimitMax  | rateLimitWindow | endpoint      | requestsCount | responseStatusCode | responseBody                   |
  | 45            | 10000           | /health-check | 42            | 429                | { "msg": "Too Many Requests!"  |
  | 25            | 20000           | /token        | 26            | 429                | { "msg": "Too Many Requests!"  |
  | 30            | 10000           | /health-check | 29            | 200                | { "message" : "Cool!!!"" }     |
# should be done for existing endpoints so far

```

And for step definitions:
```javascript
const { When, And, Then, Given } = require('cucumber')

Given('rate limit is {int} in {int} ms', function (rateLimitMax, rateLimitWindow) {
  this.rateLimiMax = rateLimitMax
  this.rateLimitWindow = rateLimitWindow
  return 'pending' // while test is not defined yet, remove after function is done
  // I believe here you will need to mock config/test.js injecting/overwriting rateLimitMax and rateLimitWindow values
})

When('{string} the is requested {int} times in less then configurated time limit by the same client', function (endpoint, requestsCount) {
  // execute event: call endpoint requestsCount times in less then this.rateLimitMax ms by the same client
  // you can save response to this.response
  return 'pending'
})

Then('response status code should be {int}', function (responseStatusCode) {
  // assert: this.response.statusCode equal responseStatusCode
  return 'pending'
})

Then('response body should be "{string}"', function (responseBody) {
  // assert this.response.body equal responseBody
  return 'pending'
})

```

I really hope this helps @kdhttps

2020-11-25 12:23 UTC, christian-hawk commented on test/features/steps/rate-limiting-steps.js
> +  try {
About
> I think we have to start fresh server, atleast for this case. I've tried to separately start server but not getting any success. Cucumber execute every Before block first and in result we get 8090 already in used address error. I also tried to start server in Before block and stop in After but failed to stop server.

I understand that maybe you should use [`BeforeScenario`](https://github.com/cucumber/cucumber-js/blob/1.x/docs/support_files/event_handlers.md), as server already runs in global hook, you can try to:**Stop and restart server in `BeforeScenario`** and if you want you can also restart in `AfterFeature` (for other tests not to be impacted), what do you think?

2020-11-25 12:33 UTC, christian-hawk requested changes
Nicely done.
Now we just need to resolver the cucumber's 2 conversations and we are done!

2020-11-25 12:33 UTC, christian-hawk commented on test/features/rate-limiting.feature
> +Feature: Rate limiting
please confirm if it's resolved by your side (not in the PR yet)

2020-11-25 12:33 UTC, christian-hawk commented on test/features/steps/rate-limiting-steps.js
> +  try {
just commenting to add to latest review

2020-11-25 13:04 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  try {
About,

```
Scenario Outline: rateLimiter should block high rates

  Examples:

  | rateLimitMax  | rateLimitWindow | endpoint      | requestsCount | responseStatusCode | responseBody                   |
  | 45            | 10000           | /health-check | 42            | 429                | { "msg": "Too Many Requests!"  |

```

we cannot manage it as per endpoint. it is global. any endpoint you call, it count one

2020-11-25 13:06 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  try {
> try to: Stop and restart server in BeforeScenario

I tried to stop server by `server` object but failed. Give me some time, I'll try some other way

2020-11-25 13:08 UTC, kdhttps commented on test/features/rate-limiting.feature
> +Feature: Rate limiting
Not resolved yet, we need to first fix above problem https://github.com/GluuFederation/gluu-passport/pull/163#discussion_r530220214

2020-11-25 14:43 UTC, christian-hawk commented on test/features/steps/rate-limiting-steps.js
> +  try {
I see. Maybe in last case we try to add `app.on close....` to code, and then `app.emmit(...)` on test hooks.

2020-11-25 16:11 UTC, kdhttps commented
@christian-hawk I need your help, could you please reply on chat(sorry to ask here)

2020-11-30 13:26 UTC, christian-hawk commented
Can one of the admins verify this patch?

2020-11-30 13:34 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  try {
Mate, I tried all the things. Not working because even if we are closing server the node memory is not clearing. it preserving the memory state for `rate-limiter` middleware. So for solution we need new process and for that I just added one patch in package.json(not indeed but very straightforward to run rate-limiting test cases in new process)

2020-12-05 16:01 UTC, christian-hawk commented on test/features/steps/rate-limiting-steps.js
> +  try {
Ok I see, we may use this temp workaround. Using `process.*` in the code doesn't work as well?

We still need to implement the dynamic as stated here
> Agree with you.
> 
> Let's go each one of the topics you mentiones.
> 
> Dinamically using gherkin:
> 
> ```
> Scenario Outline: rateLimiter should block high rates
> 
> Given rate limit is <rateLimitMax> in <rateLimitWindow>
> When "<endpoint>" is requested <requestsCount> times in less then <rateLimitMax> by the same client
> Then response status code should be <responseStatusCode>
>   And response body should be "<responseBody>"
> 
>   Examples:
> 
>   | rateLimitMax  | rateLimitWindow | endpoint      | requestsCount | responseStatusCode | responseBody                   |
>   | 45            | 10000           | /health-check | 42            | 429                | { "msg": "Too Many Requests!"  |
>   | 25            | 20000           | /token        | 26            | 429                | { "msg": "Too Many Requests!"  |
>   | 30            | 10000           | /health-check | 29            | 200                | { "message" : "Cool!!!"" }     |
> # should be done for existing endpoints so far
> ```
> 
> And for step definitions:
> 
> ```js
> const { When, And, Then, Given } = require('cucumber')
> 
> Given('rate limit is {int} in {int} ms', function (rateLimitMax, rateLimitWindow) {
>   this.rateLimiMax = rateLimitMax
>   this.rateLimitWindow = rateLimitWindow
>   return 'pending' // while test is not defined yet, remove after function is done
>   // I believe here you will need to mock config/test.js injecting/overwriting rateLimitMax and rateLimitWindow values
> })
> 
> When('{string} the is requested {int} times in less then configurated time limit by the same client', function (endpoint, requestsCount) {
>   // execute event: call endpoint requestsCount times in less then this.rateLimitMax ms by the same client
>   // you can save response to this.response
>   return 'pending'
> })
> 
> Then('response status code should be {int}', function (responseStatusCode) {
>   // assert: this.response.statusCode equal responseStatusCode
>   return 'pending'
> })
> 
> Then('response body should be "{string}"', function (responseBody) {
>   // assert this.response.body equal responseBody
>   return 'pending'
> })
> ```
> 
> I really hope this helps @kdhttps

2020-12-05 16:02 UTC, christian-hawk requested changes
Still have an unresolved conversation from former review to dinamically tests endpoints behaviour.

2020-12-05 16:12 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  try {
I tried `process` utils mate, but not getting success. It exit the cucumber process

2020-12-07 07:15 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  try {
@christian-hawk  mate, so what you think about this now?

2020-12-09 07:05 UTC, kdhttps commented
@christian-hawk what you think now? https://github.com/GluuFederation/gluu-passport/pull/163#discussion_r537277879

2020-12-11 15:54 UTC, christian-hawk requested changes
Well done made.
We just need to do the correct `features` and `steps` dynamically

2020-12-11 15:54 UTC, christian-hawk commented on test/features/steps/enpoint-metric-steps.js
>  BeforeAll({ timeout: 600 * 1000 }, (done) => {
wooow this is fancy! 💯

2020-12-11 15:54 UTC, christian-hawk commented on test/rate-limiter.test.js
> +/* eslint-disable security/detect-non-literal-fs-filename */
well done mate, happy to see this! 👍🏻

2020-12-11 15:54 UTC, christian-hawk commented on test/app-factory.test.js
> +    const appUseSpy = spyOnAppUse()
🖤

2020-12-11 15:55 UTC, christian-hawk commented
I'm changing this to draft as it's still a work in progress.

2020-12-16 21:00 UTC, christian-hawk submitted a review, later dismissed
Very nice structure.
Please check priority comments on `rate-limiting-steps.js`. I understand after that we are done.

2020-12-17 07:19 UTC, kdhttps commented on server/app.js
> +    module.exports = httpServer
Yes, we need it to close app in test cases i.e. `app.close()`

2020-12-17 07:21 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  const appStart = new Promise((resolve, reject) => {
mate, right but `BeforeStep` hook is not available now in cucumber-js. it is in dev now https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#added so I added it in `Given`

2020-12-17 07:27 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  const app = require('../../../server/app')
Yes, I tried to mock and stud, the rateLimiter, config, appfactory but its failed to overwrite this all. so for now I used config which is set in test.js

2020-12-17 07:38 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +    if (i <= rateLimitMax) {
Wow :heart:  , Agree Mate, thank you for sharing this valuable concept details. I like second suggestion `Then last request response should have status code <code>`

2020-12-17 12:24 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  const app = require('../../../server/app')
@christian-hawk mate, it will be good if you try to stub it

2021-01-06 11:42 UTC, kdhttps commented on test/features/steps/rate-limiting-steps.js
> +  const app = require('../../../server/app')
@christian-hawk mate, could you please take a look here?

2021-01-11 16:15 UTC, christian-hawk commented
here we can see that rate limiting counting is not being reset for each scenario example, I'm working on that.

I also changed to static config values, you got a point here.

After thinking I also understand that changing config file may go to our blackbox stage-testing instead of our whitebox functional tests (here).

2021-01-11 18:44 UTC, christian-hawk commented
run tests

2021-01-11 18:49 UTC, christian-hawk commented
As you requested, I did the changes for accurate tests.
Now we need only to check codacy reports and maybe create a helper or cucumber setup.js to avoid dry.

2021-01-11 18:49 UTC, christian-hawk commented on test/features/steps/rate-limiting-steps.js
> +  const app = require('../../../server/app')
After thinking I also understand that changing config file may go to our blackbox stage-testing instead of our whitebox functional tests (here).

2021-01-11 19:26 UTC, christian-hawk commented
run tests

2021-01-11 19:31 UTC, christian-hawk commented
run tests

2021-01-12 09:09 UTC, kdhttps commented
run tests

2021-01-18 15:46 UTC, christian-hawk commented
run tests

2021-01-18 16:34 UTC, christian-hawk commented
@kdhttps 
IDP initiated flow failed:
```sh
13:04:45 ============================================================================
13:04:45 
13:04:45 - Provider type: IDP
13:04:45 - Type: passport-saml
13:04:45 - Flow: idp-initiated
13:04:45 - Passport Provider ID: saml-idpinit
13:04:45 TODO: Creating Trust Relation on t3.techno24x7.com automatically
13:04:45 
13:04:45 - User data:
13:04:45 USER_NAME: hansdoe
13:04:45 USER_PASSWORD: test123
13:04:45 USER_MAIL: hansdoe@test.com
13:04:45 USER_GIVEN: hans
13:04:45 USER_SUR: doe
13:04:45 
13:04:45 ----------------------------------------------------------------------------
13:04:45 RUNNING BLACKBOX BDT TESTS:
13:04:45 ----------------------------------------------------------------------------
13:04:45 
13:04:45 Feature: accessing protected content # tests/behaver/features/protected-content.feature:1
13:04:50 
13:04:50   Scenario: Not authenticated user access protected content  # tests/behaver/features/protected-content.feature:3
13:04:50     Given that user exists in provider                       # tests/behaver/features/steps/protected-content.py:37
13:04:50     When user tries to access protected content page         # tests/behaver/features/steps/protected-content.py:126
13:04:54     Then user should be redirected to login page             # tests/behaver/features/steps/protected-content.py:140
13:05:08 
13:05:08   Scenario: Authenticated user access protected content  # tests/behaver/features/protected-content.feature:9
13:05:08     Given that user exists in provider                   # tests/behaver/features/steps/protected-content.py:37
13:05:08     And user is authenticated                            # tests/behaver/features/steps/protected-content.py:42
13:05:25 (None, None, None)
13:05:25       Traceback (most recent call last):
13:05:25         File "/var/lib/jenkins/.cache/pypoetry/virtualenvs/gluu-passport-testing-_NjlDPuR-py3.6/lib/python3.6/site-packages/behave/model.py", line 1329, in run
13:05:25           match.run(runner.context)
13:05:25         File "/var/lib/jenkins/.cache/pypoetry/virtualenvs/gluu-passport-testing-_NjlDPuR-py3.6/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
13:05:25           self.func(context, *args, **kwargs)
13:05:25         File "tests/behaver/features/steps/protected-content.py", line 121, in user_authenticates
13:05:25           assert context.web.current_url.startswith(context.base_url)
13:05:25       AssertionError
13:05:25 
13:05:26     When user tries to access protected content page     # None
13:05:26     Then user should access protected content            # None
13:05:26 
13:05:26 
13:05:26 Failing scenarios:
13:05:26   tests/behaver/features/protected-content.feature:9  Authenticated user access protected content
13:05:26 
13:05:26 0 features passed, 1 failed, 0 skipped
13:05:26 1 scenario passed, 1 failed, 0 skipped
13:05:26 4 steps passed, 1 failed, 2 skipped, 0 undefined
13:05:26 Took 0m29.508s
13:05:26 entered teardown...
```

Basically it says we are not getting in the desired URL at this point.
Would you test the flow manually?

2021-01-18 17:09 UTC, kdhttps commented
> Basically it says we are not getting in the desired URL at this point.
Would you test the flow manually?

No Mate, I'll test it

2021-01-19 06:54 UTC, kdhttps commented
run tests

2021-01-20 12:52 UTC, kdhttps commented
run tests

2021-01-25 08:20 UTC, kdhttps commented
run tests

2021-01-25 09:21 UTC, kdhttps commented
run tests

2021-01-25 09:52 UTC, kdhttps commented
run tests

2021-01-27 10:03 UTC, kdhttps commented
run tests

2021-01-28 07:57 UTC, kdhttps commented
run tests

2021-01-28 08:28 UTC, kdhttps commented
run tests

2021-01-28 09:03 UTC, kdhttps commented
run tests

2021-01-28 09:23 UTC, kdhttps commented
run tests

2021-01-28 12:09 UTC, kdhttps commented
run tests

2021-01-28 13:29 UTC, kdhttps commented
run tests

2021-01-29 09:30 UTC, kdhttps commented
run tests

2021-02-01 12:52 UTC, kdhttps commented
run tests

2021-02-01 13:50 UTC, kdhttps commented
run tests

2021-02-01 14:09 UTC, kdhttps commented
run tests

2021-02-01 16:49 UTC, kdhttps commented
run tests

2021-02-01 17:42 UTC, kdhttps commented
Test are passing on my local machine. so we can merge this PR. @christian-hawk may I merge this PR??

```
PLEASE DO NOT INTERRUPT
============================================================================
Configuration is loading from test.conf file
============================================================================
Setting up environment....
PASSPORT_HOST=xxxx
PASSPORT_IP=xxxx
PROVIDER_HOST=xxxx
PROVIDER_IP=xxxxx
PROVIDER_SNAPSHOT_ID=xxxxx
CLIENT_HOST=dev.xxxx
API_CLIENT_ID=5aba39e9-xxxx
API_CLIENT_SECRET=xxxx
LATEST_DEV_SNAPSHOT_ID=xxx
LATEST_STABLE_SNAPSHOT_ID=xx
============================================================================
create_drplet=false
run_tests=true
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   299  100   202  100    97    108     52  0:00:01  0:00:01 --:--:--   161
{}
Creating test user on xxxxx...
Token generated:xxxx
Error creating user, please check.
response status: 500
reponse: b''
Setting up test client with pre-selected provider saml-default...
https://xxxx/configuration
{
  "provider_id": "saml-default"
}
============================================================================

STARTING: PASSPORT-SAML-DEFAULT

============================================================================

- Provider type: IDP
- Type: passport-saml
- Flow: default
- Passport Provider ID: saml-default
TODO: Creating Trust Relation on xxxx automatically

- User data:
USER_NAME: johndoe22
USER_PASSWORD: test123
USER_MAIL: johndoe22@test.ocom
USER_GIVEN: john
USER_SUR: doe

----------------------------------------------------------------------------
RUNNING BLACKBOX BDT TESTS:
----------------------------------------------------------------------------

Feature: accessing protected content # tests/behaver/features/protected-content.feature:1

  Scenario: Not authenticated user access protected content  # tests/behaver/features/protected-content.feature:3
    Given that user exists in provider                       # tests/behaver/features/steps/protected-content.py:37 0.000s
    When user tries to access protected content page         # tests/behaver/features/steps/protected-content.py:133 9.524s
    Then user should be redirected to login page             # tests/behaver/features/steps/protected-content.py:148
    Then user should be redirected to login page             # tests/behaver/features/steps/protected-content.py:148 8.016s

  Scenario: Authenticated user access protected content  # tests/behaver/features/protected-content.feature:9
    Given that user exists in provider                   # tests/behaver/features/steps/protected-content.py:37 0.000s
    And user is authenticated                            # tests/behaver/features/steps/protected-content.py:42
    And user is authenticated                            # tests/behaver/features/steps/protected-content.py:42 32.119s
    When user tries to access protected content page     # tests/behaver/features/steps/protected-content.py:133 5.172s
    Then user should access protected content            # tests/behaver/features/steps/protected-content.py:168 0.045s

1 feature passed, 0 failed, 0 skipped
2 scenarios passed, 0 failed, 0 skipped
7 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m54.877s

----------------------------------------------------------------------------

BLACKBOX BDT TESTS FINISHED FOR TEST CASE: PASSPORT-SAML-DEFAULT
============================================================================
Deleting test users on xxx...
User deleted from idp/oidc provider via API.
Creating test user on xxx...
Token generated: 39deca64-c349-41f3-ba42-06b644ce79f3
User created with success via API...
b'{"inum":"3e7e5a9c-c005-48e4-a232-c0c212ded3d9","surName":"doe","givenName":"john","email":"jo-sef@test.com","password":null,"userName":"josephdoe","displayName":"josephdoe","creationDate":1612169752219,"status":"ACTIVE"}'
Setting up test client with pre-selected provider saml-emailreq...
https://dev.techno24x7.com/configuration
{
  "provider_id": "saml-emailreq"
}
============================================================================

STARTING: PASSPORT-SAML-DEFAULT-EMAILREQ

============================================================================

- Provider type: IDP
- Type: passport-saml
- Flow: default emailreq
- Passport Provider ID: saml-emailreq
TODO: Creating Trust Relation on xxx automatically

- User data:
USER_NAME: josephdoe
USER_PASSWORD: test123
USER_MAIL: jo-sef@test.com
USER_GIVEN: john
USER_SUR: doe

----------------------------------------------------------------------------
RUNNING BLACKBOX BDT TESTS:
----------------------------------------------------------------------------

Feature: accessing protected content # tests/behaver/features/protected-content.feature:1

  Scenario: Not authenticated user access protected content  # tests/behaver/features/protected-content.feature:3
    Given that user exists in provider                       # tests/behaver/features/steps/protected-content.py:37 0.000s
    When user tries to access protected content page         # tests/behaver/features/steps/protected-content.py:133 6.709s
    Then user should be redirected to login page             # tests/behaver/features/steps/protected-content.py:148
    Then user should be redirected to login page             # tests/behaver/features/steps/protected-content.py:148 8.013s

  Scenario: Authenticated user access protected content  # tests/behaver/features/protected-content.feature:9
    Given that user exists in provider                   # tests/behaver/features/steps/protected-content.py:37 0.000s
    And user is authenticated                            # tests/behaver/features/steps/protected-content.py:42
    And user is authenticated                            # tests/behaver/features/steps/protected-content.py:42 39.887s
    When user tries to access protected content page     # tests/behaver/features/steps/protected-content.py:133 5.160s
    Then user should access protected content            # tests/behaver/features/steps/protected-content.py:168 0.075s

1 feature passed, 0 failed, 0 skipped
2 scenarios passed, 0 failed, 0 skipped
7 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m59.844s

----------------------------------------------------------------------------

BLACKBOX BDT TESTS FINISHED FOR TEST CASE: PASSPORT-SAML-DEFAULT-EMAILREQ
============================================================================
Deleting test users on xxx...
User deleted from idp/oidc provider via API.
Creating test user on xxx...
Token generated: 417061f8-21f1-4b21-8360-68973db7ce47
User created with success via API...
b'{"inum":"186fc964-5d4b-4cc3-be86-7458b67594e9","surName":"doe","givenName":"john","email":"jo-sef@test.com","password":null,"userName":"josephdoe2","displayName":"josephdoe2","creationDate":1612169825885,"status":"ACTIVE"}'
Setting up test client with pre-selected provider saml-emaillink...
https://dev.techno24x7.com/configuration
{
  "provider_id": "saml-emaillink"
}
============================================================================

STARTING: PASSPORT-SAML-DEFAULT-EMAILLINK

============================================================================

- Provider type: IDP
- Type: passport-saml
- Flow: default emaillink
- Passport Provider ID: saml-emaillink
TODO: Creating Trust Relation on xxx automatically

- User data:
USER_NAME: josephdoe2
USER_PASSWORD: test123
USER_MAIL: jo-sef@test.com
USER_GIVEN: john
USER_SUR: doe

----------------------------------------------------------------------------
RUNNING BLACKBOX BDT TESTS:
----------------------------------------------------------------------------

Feature: accessing protected content # tests/behaver/features/protected-content.feature:1

  Scenario: Not authenticated user access protected content  # tests/behaver/features/protected-content.featu [...]

2021-02-01 17:44 UTC, christian-hawk commented
Just a note: as jenkins automated tests are in alpha, when we find jenkins problem we run tests locally and merge.

2021-02-01 17:46 UTC, christian-hawk approved these changes

2021-02-01 18:01 UTC, merged