Replace request with war in uma.js
GluuFederation/gluu-passport pull request #211
Opened 2021-02-09 09:42 UTC by kdhttps

close #205

2021-02-09 20:40 UTC, christian-hawk requested changes
I'm impressed with your testing and good practices evolution.

Please kindly check my request comments.

2021-02-09 20:40 UTC, christian-hawk commented on package.json
> -    "request": "^2.88.0",
`got` is still in `devDependencies` object. Shouldn't it be in `dependencies' ?

2021-02-09 20:40 UTC, christian-hawk commented on server/utils/uma.js
> +      if (tokenEndpoint) {
`tokenEndpoint`! Nice, clean coding 👨🏻‍🎤

2021-02-09 20:40 UTC, christian-hawk commented on server/utils/uma.js
> +          `getConfiguration. parsed.params = ${JSON.stringify(parsed.parms)}`
should it be `parsed.parms`, not `parsed.params`? 
If this is wrong, a test should break it. If not, it's all good.

2021-02-09 20:40 UTC, christian-hawk commented on test/configDiscovery.test.js
> +/* eslint-disable security/detect-non-literal-fs-filename */
you are getting better on it.

2021-02-10 04:38 UTC, kdhttps commented on package.json
> -    "request": "^2.88.0",
Right, I'll add it in `dependencies`.

2021-02-10 04:42 UTC, kdhttps commented on server/utils/uma.js
> +          `getConfiguration. parsed.params = ${JSON.stringify(parsed.parms)}`
`parsed.parms` is correct one.

2021-02-10 04:42 UTC, kdhttps commented on test/configDiscovery.test.js
> +/* eslint-disable security/detect-non-literal-fs-filename */
thanks mate :)

2021-02-10 12:30 UTC, christian-hawk approved these changes

2021-02-10 12:32 UTC, merged