feat(package.json): support node 14.16.0 to 15.11.0
GluuFederation/gluu-passport pull request #230
Opened 2021-03-10 13:43 UTC by kdhttps

close #213

2021-03-11 19:15 UTC, christian-hawk commented
run tests 🤞🏻

2021-03-11 19:22 UTC, christian-hawk requested changes
We also need to 
- [ ] update CI test to run on the allowed versions (and keep 12 too for now) here: https://github.com/GluuFederation/gluu-passport/blob/d81776dbfefdd74bf3ffc7ee35961f7ee2200e09/.github/workflows/codecov.yml#L26
-

2021-03-11 19:22 UTC, christian-hawk commented on package.json
> +    "node": ">=14.16.0 <=15.11.0"
should we allow 15? As I checked latest stable is 14. (and also requested by CN team)

2021-03-11 20:23 UTC, christian-hawk commented
run tests

2021-03-11 21:23 UTC, christian-hawk commented
run tests

2021-03-12 07:40 UTC, kdhttps commented on package.json
> +    "node": ">=14.16.0 <=15.11.0"
> should we allow 15?

Not sure. but I think No. let's only use `=14.16.0`. what you think?

2021-03-12 11:42 UTC, christian-hawk commented on package.json
> +    "node": ">=14.16.0 <=15.11.0"
I think we should restrict to 14 then. so `>=14.16.0 <15.0.0` ?

2021-03-12 11:46 UTC, kdhttps commented on package.json
> +    "node": ">=14.16.0 <=15.11.0"
Agreed

2021-03-12 13:45 UTC, christian-hawk commented
run tests

2021-03-15 21:48 UTC, christian-hawk commented
run tests

2021-03-15 22:11 UTC, christian-hawk commented
run tests

2021-03-15 22:59 UTC, christian-hawk commented
run tests

2021-03-15 23:56 UTC, christian-hawk commented
run tests

2021-03-16 00:08 UTC, christian-hawk commented
run tests

2021-03-16 00:35 UTC, christian-hawk commented
run tests

2021-03-17 21:11 UTC, christian-hawk commented
run tests

2021-03-17 21:44 UTC, christian-hawk commented
run tests

2021-03-18 01:44 UTC, christian-hawk commented
run tests

2021-03-18 02:27 UTC, christian-hawk commented
run tests

2021-03-18 09:35 UTC, kdhttps commented on .github/workflows/codecov.yml
> +        node-version: [14.x]
I think no, The EOL for Node 12 is `2022-04-30`. what you think now?

2021-03-22 07:21 UTC, kdhttps commented on .github/workflows/lint.yml
> +        node-version: [14.x]
I think no, The EOL for Node 12 is 2022-04-30. what you think now?

2021-03-22 12:28 UTC, kdhttps commented
About,
> can we keep 12 as well?
I think no, The EOL for Node 12 is 2022-04-30. what you think now?


About, `Node version 12 on gluu and still deps are installing on jenkins test cases.`
@christian-hawk  Mate, I've tested on local and server, inside gluu ce chroot. it is preventing deps installation. so I think, now we need to test it on droplets. so could you please suggest how do I check on jenkins droplets??

2021-03-22 12:36 UTC, christian-hawk commented on .github/workflows/codecov.yml
> +        node-version: [14.x]
I think we can run tests on 12 till EOL of at least for some transiction time, what are the cons of it?

2021-03-22 12:42 UTC, kdhttps commented on .github/workflows/codecov.yml
> +        node-version: [14.x]
The Confusion. It will create confusion, dirty and maintenance. Also No benefits as we are focusing on `>=14.x.x`.

2021-04-12 15:50 UTC, christian-hawk commented on .github/workflows/lint.yml
> +        node-version: [14.x]
as discussed with abu, lets keep 12 for a while so we can keep some gluu-server backwards compatibility, otherwise we would need to create a parallel branch for 4.2.x (x=fix) in case a fix is needed and a new 4.2.x gluu-server is released.
Mantaining a parallell branch also would require different tests (as different node version required) on CI flow.
So I understand we should avoid parallel branches if possible, is this case.

So  we need to allow node 12 until 4.2.x reaches end of life.

Are you ok with that?

2021-04-14 13:46 UTC, christian-hawk commented
run tests

2021-04-14 15:13 UTC, christian-hawk approved these changes
nice work.

2021-04-14 15:14 UTC, merged