twitter security
GluuFederation/gluu-passport pull request #269
Opened 2021-05-03 10:18 UTC by kdhttps

Make a custom error handle and override the existing one so that it will parse thru xml parser.

closes #265

2021-05-06 20:14 UTC, christian-hawk requested changes
Hey mate nice approach.
I did some comments.

2021-05-06 20:14 UTC, christian-hawk commented on test/twitter-error-handler.spec.js
> +})
We need to test throwing error (json and xml?) using a twitter json / xml examples. 
this can be done here or even creating a cucumber test scenario. Whatever you preffer.

2021-05-06 20:14 UTC, christian-hawk commented on server/app-factory.js
> +    twitterErrorHandler()
This is a really interesting approach. Preloading modules without an `if`.
But after analizing deeper, I'm not sure this will be possible.
- Perfomance reasons: load twitter module even if user does not uses twitter
- Wouldn't module be loaded twice as per `setupStrategy` in `providers.js`?

2021-05-07 13:18 UTC, kdhttps commented on server/app-factory.js
> +    twitterErrorHandler()
> Perfomance reasons: load twitter module even if user does not uses twitter

I think no, it just overriding function.

 > Wouldn't module be loaded twice as per setupStrategy in providers.js?

Nope, it just overriding. I tested normal login with twitter and it is working good.

2021-05-07 13:29 UTC, kdhttps commented on test/twitter-error-handler.spec.js
> +})
mate, I think no need to try with twitter json / xml as passport just call `parseErrorResponse` function [here](https://github.com/jaredhanson/passport-oauth1/blob/master/lib/strategy.js#L393) in strategy and it calls override function which we already tested. Let me know what you think?

2021-05-10 12:30 UTC, christian-hawk requested changes
Comments to discuss

2021-05-10 12:30 UTC, christian-hawk commented on server/app-factory.js
> +    twitterErrorHandler()
Thanks for clarify. I understand you override it and load it w/ overriden on app initialization, so:
>>Perfomance reasons: load twitter module even if user does not uses twitter

>I think no, it just overriding function.
1. But we are loading a module even if we don't use it, right? Loaded module is not allocated in memory?
>> Nope, it just overriding. I tested normal login with twitter and it is working good.
2. After overriden module is called, it will be loaded again here:
https://github.com/GluuFederation/gluu-passport/blob/302968b7376cc5478dac513f6ce98496f3bcb91f/server/providers.js#L78
So are you sure is **not being loaded twice**?
3. When you say you tested twitter login an it works, it would work even without the fix. Have we tested error handling in login flow?

2021-07-08 08:47 UTC, closed without merging