feat(httpProxy): add support to global http proxy
GluuFederation/gluu-passport pull request #333
Opened 2021-08-27 14:54 UTC by kdhttps

add configuration and feature to use http proxy

close #331 

Currently, this configuration is not available in oxTrust. You need to export environment variables:

| Property | Description |
|----------|-------------|
| HTTP_PROXY | Sets HTTP proxy to use |
| HTTPS_PROXY | Sets a distinct proxy to use for HTTPS requests.|
| NO_PROXY | Specifies a pattern of URLs that should be excluded from proxying.|

2021-08-30 04:08 UTC, christian-hawk requested changes
Thanks for that, @kdhttps 👍🏻 . Please check my comments.

2021-08-30 04:08 UTC, christian-hawk commented on config/test.js
> +const HTTP_PROXY = 'http://localhost:3128'
This is a specific cenário setting, my understanding is that it should stay in the specific test `before()` hook.
Otherwise all tests will be ran with this setting.

2021-08-30 04:08 UTC, christian-hawk commented on test/http-global-proxy.spec.js
> +  it('node global object should have global agent and proxy setup', async () => {
There are too many asserts for one single test. Could you please split them? Ideal is 1 for 1.

2021-08-30 04:08 UTC, christian-hawk commented on test/http-global-proxy.test.js
> +  it('node global object should have global agent and proxy setup', async () => {
Also here too many asserts for one test, is it possible to split?

2021-08-30 04:08 UTC, christian-hawk commented on config/production.js
> +  HTTP_PROXY: process.env.HTTP_PROXY,
Question: why aren't we also loading `HTTPS_PROXY`? ref: https://docs.cloudfoundry.org/cf-cli/http-proxy.html#format

2021-08-30 06:53 UTC, kdhttps commented on config/test.js
> +const HTTP_PROXY = 'http://localhost:3128'
No, Don't worry, we have setup NO_PROXY. It will not affect other test cases.

2021-08-30 06:54 UTC, kdhttps commented on test/http-global-proxy.spec.js
> +  it('node global object should have global agent and proxy setup', async () => {
sure

2021-08-30 07:29 UTC, kdhttps commented on test/http-global-proxy.test.js
> +  it('node global object should have global agent and proxy setup', async () => {
agreed, i'll update

2021-08-30 07:52 UTC, kdhttps commented on config/production.js
> +  HTTP_PROXY: process.env.HTTP_PROXY,
default, global-agent uses http proxy settings if there is no https proxy setting https://github.com/gajus/global-agent#separate-proxy-for-https. let me know mate, if we still want to keep it seperate

2021-08-30 08:22 UTC, kdhttps commented on config/production.js
> +  HTTP_PROXY: process.env.HTTP_PROXY,
ok i think let's play safe and keep it separate and give me your confirmation and I'll make a final change

2021-08-30 13:53 UTC, christian-hawk commented on config/production.js
> +  HTTP_PROXY: process.env.HTTP_PROXY,
agree mate

2021-08-30 13:54 UTC, christian-hawk commented on config/test.js
> +const HTTP_PROXY = 'http://localhost:3128'
ok thanks!

2021-08-30 15:19 UTC, kdhttps commented
@christian-hawk mate before merging this, take a look at one thing here https://github.com/gajus/global-agent/issues/23. I am not finding any worry about this. Whoever uses this HTTPS layer on a proxy server in internal clusters is crazy.

2021-08-31 15:36 UTC, christian-hawk commented
> @christian-hawk mate before merging this, take a look at one thing here [gajus/global-agent#23](https://github.com/gajus/global-agent/issues/23). I am not finding any worry about this. Whoever uses this HTTPS layer on a proxy server in internal clusters is crazy.

So do you believe we should rollback https://github.com/GluuFederation/gluu-passport/pull/333/commits/f6cbffb27d5870bf71c288b8518ce6d25c4b2bdd ? If yes, no prob.

2021-08-31 17:43 UTC, kdhttps commented
> So do you believe we should rollback f6cbffb ? If yes, no prob.

No, No Mate, it is completely OK, In fact, it is a completely different story than gajus/global-agent#23. Both are different cases.
1. HTTPS_PROXY: it uses for HTTPS proxy, I mean applications to use this setting to call an external HTTPS endpoint. which is currently working well. No problem with it. Well setuped app always uses HTTP layer proxy. The proxy server exposes an HTTP endpoint to allow internet access on an internal network. but in point 2
2. Point 2 gajus/global-agent#23: proxy server expose HTTPS endpoint to allow internet on an internal network. which is really look bad setup, increase super CPU usage

so I think no need to worry about point 2. please share your thoughts

2021-09-01 18:00 UTC, christian-hawk approved these changes
So we take this in consideration and merge.

2021-09-01 18:35 UTC, christian-hawk commented
Stage tests failed on idp initiated . running again: run tests

2021-09-01 20:32 UTC, christian-hawk commented
run tests

2021-09-02 07:05 UTC, kdhttps commented
@christian-hawk test passed

2021-09-03 14:23 UTC, christian-hawk commented
@kdhttps would you please edit the PR text explaining how to setup it and also open a PR on docs?

2021-09-03 15:05 UTC, kdhttps commented
> @kdhttps would you please edit the PR text explaining how to setup it and also open a PR on docs?

@christian-hawk  mate, edited PR text, please review then I'll add same in docs

2021-09-03 17:53 UTC, kdhttps commented
@christian-hawk mate, also created docs PR here https://github.com/GluuFederation/docs-gluu-server-prod/pull/73

2021-09-03 18:03 UTC, merged