fix datetime and misplace problem
GluuFederation/gluu-passport pull request #388
Opened 2021-11-15 09:22 UTC by kdhttps

ref https://github.com/GluuFederation/gluu-passport/issues/387

2021-11-15 23:52 UTC, christian-hawk requested changes
It looks like you are repeating a commit from #365 that has already been merged. If not, can you please explain?

2021-11-15 23:52 UTC, christian-hawk commented on test/logging.spec.js
> +    // YYYY-MM-DD HH
What is triggering the action? What is being logged?

2021-11-16 08:08 UTC, kdhttps commented on test/logging.spec.js
> +    // YYYY-MM-DD HH
I think you missed my comment https://github.com/GluuFederation/gluu-passport/issues/387#issuecomment-968694782

- [x] it should be an placed in an integration test, not an unit test
- [x] assert.include should be used, to ensure proper assertion messages from chai
- [ ] there should be an action trigger

The last one remains. could you please describe?

2022-01-18 20:37 UTC, christian-hawk commented
@kdhttps could you please solve conflict?

2022-01-19 07:19 UTC, kdhttps commented on test/logging.spec.js
> +    // YYYY-MM-DD HH
Done mate

2022-01-19 07:20 UTC, kdhttps commented
> @kdhttps could you please solve conflict?

Done mate, please review!

2022-01-19 11:38 UTC, merged