update jose and openid-client lib latest
GluuFederation/gluu-passport pull request #397
Opened 2021-12-28 07:34 UTC by kdhttps

close #309 

Note: node engine updated. jose@4.x.x need node >= 16.13.0.

2021-12-29 15:49 UTC, christian-hawk commented
run tests

2021-12-30 00:02 UTC, christian-hawk commented
run tests

2021-12-30 00:41 UTC, christian-hawk commented
run tests

2021-12-31 21:58 UTC, christian-hawk commented
run tests

2022-01-03 13:03 UTC, christian-hawk commented
run tests

2022-01-03 13:23 UTC, christian-hawk commented
run tests

2022-01-03 18:23 UTC, christian-hawk commented
run tests

2022-01-03 20:49 UTC, christian-hawk requested changes
Please check comments regarding integration and unit tests, thanks for the PR.

2022-01-03 20:49 UTC, christian-hawk commented on test/openid-client-helper.spec.js
> +    it('make sure jwks has keys, kid, n and kty', () => {
please create separate tests "should have keys", "should have kid", ....

2022-01-03 20:49 UTC, christian-hawk commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
Can we create unit tests for calling `generateKeyPair, exportJWK, calculateJwkThumbprint` using spies?

2022-01-03 20:55 UTC, christian-hawk requested changes
added node version comment

2022-01-03 20:55 UTC, christian-hawk commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
as you said "jose@4.x.x need node >= 16.13.0." , but:
-  `"node": ">=12.19.0 <=16.13.0"` would accept 12, 14... will it work with previous versions?
- what node version is gluu-server using to run passport?

2022-01-04 08:21 UTC, kdhttps commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
> what node version is gluu-server using to run passport?

v14.16.1

> "node": ">=12.19.0 <=16.13.0" would accept 12, 14... will it work with previous versions?

First pardon, it is needed by openid-client. openid-client allows only some versions `"node": "^12.19.0 || ^14.15.0 || ^16.13.0"`
https://github.com/panva/node-openid-client/blob/main/package.json#L74

IMO, we should use 16.13.0 in gluu server also. Let me know mate, your thoughts

2022-01-04 08:23 UTC, kdhttps commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
I tried to spy on these functions using `sinon` but did not get any success. `sinon` is not really allowed spying on the standalone functions. Could you please try mate?

2022-01-04 08:58 UTC, kdhttps commented on test/openid-client-helper.spec.js
> +    it('make sure jwks has keys, kid, n and kty', () => {
agreed, done!

2022-01-07 00:59 UTC, christian-hawk commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
>> "node": "^12.19.0 || ^14.15.0 || ^16.13.0
So it will work with previous versions, right? 16 is not needed now. Correct?

2022-01-07 01:01 UTC, christian-hawk commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
can you show what you've tried and what's the output, please? It should be something like
`sinon.spy(jose, 'generateKeyPair')`.

2022-01-07 07:32 UTC, kdhttps commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
sure mate, 
I tried this
```js
    it('should call generateKeyPair', async () => {
      console.log(jose.generateKeyPair) // [AsyncFunction: generateKeyPair] 
      const generateKeyPairSpy = sinon.spy(jose, 'generateKeyPair')
      await generateJWKS({ id: 'testProvider' })
      assert.isTrue(generateKeyPairSpy.called)
    })
```

But sinon throwing error
```
TypeError: Attempted to wrap undefined property generateKeyPair as function
```

You can see `console.log(jose.generateKeyPair)` prints `[AsyncFunction: generateKeyPair] ` but sinon not able to find function/property of jose.

2022-01-07 07:39 UTC, kdhttps commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
Yes we can use any one of from this 3 `"node": "^12.19.0 || ^14.15.0 || ^16.13.0`

2022-01-07 07:59 UTC, kdhttps commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
If we decided to choose the previous version then we need to use `14.15.0`. Note: we have now `14.16.1` which does not work as per the condition. That is why I am thinking to use `16.13.0`. please share your view

2022-01-07 20:16 UTC, christian-hawk commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
Thanks for sharing your try, mate. 👊🏻 
 
So after digging `jose` code and **Sinon** docs....

Actually yes: it finds  "_function/property of jose_".

So you can think about jose:

something like:
```javascript
const jose = {
   generateKeyPair: () => { return 'theSuperKeyPair '}
}
```

You will find several issues on **Sinon** repo related to **spying on properties** (and also on **Getters**).

The way to achieve it, is:
```js
const generateKeyPairSpy = sinon.spy()
sinon.stub(jose, 'generateKeyPair').value(generateKeyPairSpy)
```

So basically:
```javascript
    it('should call generateKeyPair once', async () => {
      const generateKeyPairSpy = sinon.spy()
      sinon.stub(jose, 'generateKeyPair').value(generateKeyPairSpy)
      jose.generateKeyPair('')
      console.log(generateKeyPairSpy.callCount) // 1
      assert(generateKeyPairSpy.calledOnce)
    })
```

Anyway if you debug `jose` object you gonna see that `generateKeyPair` has a `Getter`.

So in **Sinon Spy** docs, in the **section about spying objects with getters and setters**, you gonna find that this would be the best approach:

```js
it('should call generateKeyPair once', async () => {
      console.log(JSON.stringify(jose))
      const getterSpy = sinon.spy(jose, 'generateKeyPair', ['get'])
      jose.generateKeyPair('')
      assert(getterSpy.get.calledOnce)
 })
```

Hope it helps mate.

2022-01-08 14:52 UTC, christian-hawk commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
I'm still not understanding why would be a problem to use `14.16.1` as specs says `^14.15.0` and not `<=14.15.0`, maybe I'm missing something?

2022-01-08 17:36 UTC, kdhttps commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
Sorry, I miss interpreted the `^` in the version. But I would like to add `"node": "^12.19.0 || ^14.15.0 || ^16.13.0` engine condition in our package.json. what do you think mate?

2022-01-08 18:26 UTC, kdhttps commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
Thank you mate. But still not working when we tried this with `await generateJWKS({ id: 'testProvider' })`.
```js
it('should call generateKeyPair once', async () => {
      const generateKeyPairSpy = sinon.spy(jose, 'generateKeyPair', ['get'])
      // jose.generateKeyPair('')
      await generateJWKS({ id: 'test' })
      console.log(generateKeyPairSpy.callCount) // returning undefined
      assert.isTrue(generateKeyPairSpy.get.calledOnce) // returning false
    })
```

2022-01-08 19:07 UTC, christian-hawk commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
Ok but why?

2022-01-10 11:55 UTC, kdhttps commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
no idea mate, trying to find...

2022-01-11 09:19 UTC, kdhttps commented on server/utils/openid-client-helper.js
> +  const { privateKey, publicKey } = await generateKeyPair('RS256')
@christian-hawk fixed Sinon spy problem, please latest changes

2022-01-15 23:11 UTC, christian-hawk commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
No problem mate. I think you should open a new issue to change node version to 16, as a separate one.

2022-01-17 05:50 UTC, kdhttps commented on package.json
> +    "node": ">=12.19.0 <=16.13.0"
sure created https://github.com/GluuFederation/gluu-passport/issues/407
I think we fix all issues for this PR so you can review and merge this PR :)

2022-01-18 19:49 UTC, christian-hawk approved these changes

2022-01-18 20:24 UTC, merged