package.json - update node engines
GluuFederation/gluu-passport pull request #410
Opened 2022-01-18 06:42 UTC by kdhttps

close #407

2022-03-21 04:00 UTC, christian-hawk requested changes

2022-03-21 04:00 UTC, christian-hawk commented on package.json
> +    "node": "^12.19.0 || ^14.15.0 || ^16.13.0"
as https://github.com/GluuFederation/gluu-passport/pull/397/files#r785360818 I thought we were gonna move to 16 only. Why do we still need 12 and 14?

2022-03-21 05:14 UTC, kdhttps commented on package.json
> +    "node": "^12.19.0 || ^14.15.0 || ^16.13.0"
No mate, Our passport supports 14 and 16 both. I will remove 12.

2022-03-21 07:02 UTC, kdhttps commented on package.json
> +    "node": "^12.19.0 || ^14.15.0 || ^16.13.0"
Done! @christian-hawk  mate, do you also want me to update the github workflows?

2022-03-31 06:17 UTC, kdhttps commented
run tests

2022-06-17 19:55 UTC, christian-hawk commented
surpassed by #451

2022-06-17 19:55 UTC, closed without merging