feat(production.js): rate limit config from env
GluuFederation/gluu-passport pull request #452
Opened 2022-06-16 12:20 UTC by kdhttps

close #450

2022-06-17 18:45 UTC, christian-hawk approved these changes

2022-06-17 18:55 UTC, christian-hawk requested changes

2022-06-17 18:55 UTC, christian-hawk commented on config/production.js
> +  rateLimitWindowMs: parseInt(process.env.PASSPORT_RATE_LIMIT_WINDOW_MS) || 24 * 60 * 60 * 1000, // 24 hrs in milliseconds
@kdhttps  Can you please ensure error being properly thrown if there is a string here? I think if there is an invalid string, the `parseString` does not throw Error, it just return `NaN`.

2022-06-17 18:55 UTC, christian-hawk commented on config/production.js
> +  rateLimitMaxRequestAllow: parseInt(process.env.PASSPORT_RATE_LIMIT_MAX_REQUEST_ALLOW) || 1000,
Please check codacy analysis, it looks like adding base is a good practice.

2022-06-20 06:19 UTC, kdhttps commented on config/production.js
> +  rateLimitWindowMs: parseInt(process.env.PASSPORT_RATE_LIMIT_WINDOW_MS) || 24 * 60 * 60 * 1000, // 24 hrs in milliseconds
I think it is ok because `PASSPORT_RATE_LIMIT_WINDOW_MS` is optional and if there is no `PASSPORT_RATE_LIMIT_WINDOW_MS` env setup then it will still return NaN and take the default value.

2022-06-22 17:47 UTC, kdhttps commented on config/production.js
> +  rateLimitMaxRequestAllow: parseInt(process.env.PASSPORT_RATE_LIMIT_MAX_REQUEST_ALLOW) || 1000,
done, thanks mate

2022-06-22 17:53 UTC, christian-hawk approved these changes

2022-06-22 18:04 UTC, merged