fix(security): update merger yml and saml security update in master
GluuFederation/gluu-passport pull request #502
Opened 2022-12-03 10:20 UTC by kdhttps

2022-12-04 12:37 UTC, christian-hawk requested changes
@kdhttps commit name is wrong, the commit is regarding the branch merger only. 
Also, a commit should reference only one feat/fix/etc (according to conventional commits)

The current commit should be used only for branch-merger. To add security update in master please follow the docs on `release-please`, links sent some days ago in chat.

2022-12-04 13:10 UTC, kdhttps commented
@christian-hawk I updated the last commit message, what should I do next? As per the [doc](https://github.com/googleapis/release-please#how-do-i-change-the-version-number), we can push empty commit like for example:
```
git commit --allow-empty -m "chore: release 2.0.0" -m "Release-As: 2.0.0"
```

but what should be the release number, could you please guide?

2022-12-05 15:28 UTC, christian-hawk approved these changes

2022-12-05 15:30 UTC, christian-hawk commented
@kdhttps All good for this PR. I added the **commit override** [fix release notes](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in the merged PR .

2022-12-05 15:32 UTC, merged